server:
  port: 9900
spring:
  datasource:
    url: jdbc:mysql://42.192.21.155:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  main:
    allow-circular-references: true


jwt:
  secret: 123456
  expiration: 30
  tokenHead: jwtToken
